language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: PIq7uVmu2OWXvlGCwtx13ohZSa2zwY7P0Kn0anjCTOo7BTW/iLAd6M1eZt/GTFoF2IYDLCzowEo3Ay54dbCzaFZRVZful1+8nASLljwHK4/ki/BAOfodQz31f7T7c9kF2eJdVDSJxgj2IuTLDIDqzxisbLBYBuJu+2aypv2/FeivVZOjs3sEwbZODmrvs/4QwnjP6wvrg8IwaU76eL3fLek3B0FAfkMspqsPvS0/+JAS1xvD40/bxp2vzU4hDqgly+beiCezqwEtUoEPaQYgO9uAi5TupDQ2mrkE+ypPd+bkUTiveyjRBKcMZzBmNC8XHXatTUQ4itfaMTrC8BR667/JhDIVeRAyOrG0XgJw2Ljcw2qj5vdqCxIslrg7az1oSixs7uNHIiLG/ZD9bVr2+ZNnJLYV4l8R9jDcGn5JKZXu42Hb4QXvtMjRk27EKWHeaOM33/GiJhqcUcTmQITY+31EymrysK4nDWeAbZHEhPpKF1u2bBHGZOXaK4QjXD5OEb1XfeKMGf9yUKrP3IM84BOq+3uny96jw9Ms3ZMbsWA66E1P+NAGK3vL3AaxzpBo2AfZhxFjeoTD0CY2aprtv7AMDwNW2KS0eFdy8QbrUACknZMME06ZA8vYb7XuValgEYlmN+qUuixvmJLDqrudYQrLlabI1CYxrxzq38/FwV4=
